"""add was_ai_recommended to generated_image

Revision ID: 6481d85c2633
Revises: f0e2aaf0c2c7
Create Date: 2026-04-20 09:37:03.125120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6481d85c2633'
down_revision = 'f0e2aaf0c2c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('was_ai_recommended', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_image', schema=None) as batch_op:
        batch_op.drop_column('was_ai_recommended')

    # ### end Alembic commands ###
