"""add reference_image_id to GeneratedImage

Revision ID: 85832af9eba3
Revises: b7feb046b086
Create Date: 2026-04-13 11:30:02.438610

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "85832af9eba3"
down_revision = "b7feb046b086"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "consent",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("experiment_group", sa.String(length=20), nullable=False),
        sa.Column("consented_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "experiment_session",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("experiment_group", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_ping_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("generated_image", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("reference_image_id", sa.Integer(), nullable=True)
        )
        batch_op.alter_column("hairstyle_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.create_foreign_key(None, "user_image", ["reference_image_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("generated_image", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.alter_column(
            "hairstyle_id", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.drop_column("reference_image_id")

    op.drop_table("experiment_session")
    op.drop_table("consent")
    # ### end Alembic commands ###
